# Generated by Django 4.1.1 on 2022-10-03 11:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна')),
                ('year_foundation', models.IntegerField(blank=True, verbose_name='Год основания')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс поставщика, USD')),
                ('amount_of_clients', models.IntegerField(blank=True, verbose_name='Количество покупателей')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
    ]
