# Generated by Django 4.1.1 on 2022-10-03 11:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название автосалона')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Страна')),
                ('year_foundation', models.IntegerField(blank=True, verbose_name='Год основания')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс автосалона, USD')),
                ('wish_cars', models.CharField(blank=True, max_length=500, verbose_name='Автомобили к приобретению')),
                ('list_producers', models.CharField(blank=True, max_length=500, verbose_name='Список поставщиков')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
                'ordering': ['name'],
            },
        ),
    ]
