# Generated by Django 4.1.1 on 2022-10-04 14:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_action_auto_shows_remove_action_cars_and_more'),
        ('auto_show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_show',
            name='list_auto',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Список автомобилей салона'),
        ),
        migrations.AlterField(
            model_name='auto_show',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='auto_show',
            name='list_producers',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Список поставщиков'),
        ),
        migrations.AlterField(
            model_name='auto_show',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название автосалона'),
        ),
        migrations.RemoveField(
            model_name='auto_show',
            name='wish_cars',
        ),
        migrations.AddField(
            model_name='auto_show',
            name='wish_cars',
            field=models.ManyToManyField(to='car.car', verbose_name='Автомобили к приобретению'),
        ),
    ]
