# Generated by Django 4.1.1 on 2022-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='quantity_cars_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max количество авто для применения скидки'),
        ),
        migrations.AddField(
            model_name='discount',
            name='quantity_cars_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Min количество авто для применения скидки'),
        ),
    ]
