# Generated by Django 4.1.1 on 2022-10-03 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0001_initial'),
        ('auto_show', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Бренд автомобиля')),
                ('model', models.CharField(max_length=200, verbose_name='Модель автомобиля')),
                ('year_launch', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('condition', models.CharField(blank=True, choices=[('wish_auto_show', 'желаемый для автосалона'), ('wish_customer', 'желаемый для покупателя'), ('in_showroom', 'в автосалоне'), ('at_producer', 'у производителя'), ('at_customer', 'у покупателя')], max_length=40, null=True, verbose_name='Статус авто')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена, USD')),
                ('price_discount', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой, USD')),
                ('price_action', models.IntegerField(blank=True, null=True, verbose_name='Цена по акции, USD')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('auto_shows', models.ManyToManyField(to='auto_show.auto_show', verbose_name='Автосалон')),
                ('customers', models.ManyToManyField(to='customer.customer', verbose_name='Покупатель')),
                ('producers', models.ManyToManyField(to='producer.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя скидки')),
                ('amount_discount', models.IntegerField(verbose_name='Размер скидки в %')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала скидки (dd.mm.yyyy 00:00:00)')),
                ('date_finish', models.DateTimeField(verbose_name='Дата окончания скидки (dd.mm.yyyy 00:00:00)')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='DealList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название сделки')),
                ('participants', models.CharField(choices=[('producer-showroom', 'поставщик-автосалон'), ('showroom-customer', 'автосалон-покупатель')], max_length=40, verbose_name='Стороны сделки')),
                ('price', models.IntegerField(verbose_name='Сумма сделки, USD')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения сделки')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления сделки')),
                ('auto_shows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_show.auto_show', verbose_name='Автосалон')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Авто')),
                ('customers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Покупатель')),
                ('producers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя акции')),
                ('amount_action', models.IntegerField(verbose_name='Размер скидки по акции в %')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала акции (dd.mm.yyyy 00:00:00)')),
                ('date_finish', models.DateTimeField(verbose_name='Дата окончания акции (dd.mm.yyyy 00:00:00)')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('auto_shows', models.ManyToManyField(to='auto_show.auto_show', verbose_name='Автосалон')),
                ('cars', models.ManyToManyField(to='car.car', verbose_name='Автомобиль')),
                ('producers', models.ManyToManyField(to='producer.producer', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['date_start'],
            },
        ),
    ]
