# Generated by Django 4.1.1 on 2022-10-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='auto_shows',
        ),
        migrations.RemoveField(
            model_name='action',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='action',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='deallist',
            name='auto_shows',
        ),
        migrations.RemoveField(
            model_name='deallist',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='deallist',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='deallist',
            name='producers',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='DealList',
        ),
    ]
