# Generated by Django 4.1.1 on 2022-10-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('producer', '0001_initial'),
        ('car', '0002_remove_action_auto_shows_remove_action_cars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='car',
            name='auto_shows',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_action',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_discount',
        ),
        migrations.RemoveField(
            model_name='car',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year_launch',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цвет автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бренд, модель, год автомобиля'),
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('wish_auto_show', 'желаемый для автосалона'), ('wish_customer', 'желаемый для покупателя'), ('in_showroom', 'в автосалоне'), ('at_producer', 'у производителя'), ('at_customer', 'у покупателя')], max_length=40, verbose_name='Статус авто')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена, USD')),
                ('price_discount', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой, USD')),
                ('price_action', models.IntegerField(blank=True, null=True, verbose_name='Цена по акции, USD')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('customers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Покупатель')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Автомобиль')),
                ('producers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Экземпляр автомобиля',
                'verbose_name_plural': 'Экземпляры автомобиля',
                'ordering': ['name'],
            },
        ),
    ]
